# TODO: Cache both yarn & cargo

name: 'Test'
on: 
  pull_request:
    # TODO: Graphite does not support path filters
    # paths:
    #   - 'packages/**'
    #   - 'clients/**'
    #   - 'examples/**'
    #   - '.github/workflows/**'
    #   - 'package.json'
    #   - 'yarn.lock'
    #   - 'tsconfig*.json'
    #   - 'turbo.json'
    #   - 'tsup.base.ts'
    #   - 'biome.json'
    #   - 'Cargo.toml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'
          # Note: We're not using the built-in cache here because we need to use corepack
      
      - name: Setup Corepack
        run: corepack enable
      
      - id: yarn-cache-dir-path
        name: Get yarn cache directory path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            .turbo
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-deps-
      
      - name: Install dependencies
        run: yarn install
        
      - name: Run actor-core tests
        # TODO: Add back
        # run: yarn test
        run: yarn check-types

      # - name: Install Rust
      #   uses: dtolnay/rust-toolchain@stable
      # - name: Run Rust client tests
      #   run: cd rust/client && cargo test

  # TODO: This is broken
  # test-cli:
  #   runs-on: ubuntu-latest
  #
  #   services:
  #     verdaccio:
  #       image: verdaccio/verdaccio:6
  #       ports:
  #         - 4873:4873
  #       options: --name verdaccio
  #
  #   steps:
  #       - uses: actions/checkout@v4
  #       - run: corepack enable
  #       # https://github.com/orgs/community/discussions/42127
  #       - run: /usr/bin/docker cp ${{ github.workspace }}/.verdaccio/conf/config.yaml verdaccio:/verdaccio/conf/config.yaml
  #       - run: /usr/bin/docker restart verdaccio
  #
  #       - uses: actions/cache@v4
  #         with: 
  #           path: .turbo
  #           key: ${{ runner.os }}-turbo-${{ github.sha }}
  #           restore-keys: |
  #             ${{ runner.os }}-turbo-
  #       - uses: actions/setup-node@v4
  #         with:
  #           node-version: '22.14'
  #           cache: 'yarn'
  #       - run: yarn install
  #       - run: yarn build
  #       - run: npm i -g tsx
  #       - run: ./scripts/e2e-publish.ts
  #       - run: yarn workspace @actor-core/cli run test
  #
